potential:
  kc-z:
    cutoff: 14
scale-ranges:
  repeat-count: 2
  scalables:
    - parameter:
        axis-mask: [1, 1, 0]
        guess: 2.46
        range: [2.38, 2.54]
    - uniform-layer-sep:
        guess: 3.38
        range: [3.15, 3.55]
cg:
  stop-condition:
    any:
      - value-delta:
          rel-greater-than: 0
          steps-ago: 10
#      - iterations: 300
  alpha-guess-max: 1e-1
  alpha-guess-first: 1e-2
ev-loop:
  min-positive-iter: 1
  max-iter: 3
  fail: false
ev-chase: # one-by-one
  cg:
    stop-condition:
      any:
        - value-delta:
            rel-greater-than: 0
            steps-ago: 10
        - iterations: 100
    alpha-guess-max: 1e-1
    alpha-guess-first: 1e-2
threading: "serial"
phonons:
  #supercell: {target: [35, 35, 0]}
  supercell: {target: [0, 0, 0]} # sufficient for gamma point
  disp-finder:
    rsp2:
      directions: survey
  eigensolver:
    sparse: {}
  symmetry-tolerance: 1e-3
  displacement-distance: 1e-4
layer-gamma-threshold: 0.2
bond-radius: 1.8
#lammps-update-style: { paranoid: 10 }
lammps-update-style:
  fast:
    sync-positions-every: 1

